[project]
name = "mt_reasoning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "openai>=1.102.0",
    "pandas>=2.3.2",
    "vllm>=0.10.1.1",
]
